import { type AppConfig, type ProxyConfig, type ToolMeta } from '@/shared/types';

function defaultProxy(): ProxyConfig {
  return {
    type: 'none',
    host: '',
    port: 0,
    username: '',
    password: '',
  };
}

/** 返回默认分类列表。 */
export function defaultCategories(): string[] {
  return ['AI 编程', 'IDE', '代理/网络', '设计工具', '终端'];
}

/** 返回默认工具列表。 */
export function defaultTools(): ToolMeta[] {
  return [
    {
      id: 'claude-code',
      name: 'Claude Code',
      description: '',
      logoPath: '',
      category: 'AI 编程',
      needDownload: false,
      source: { kind: 'scan', scanOnly: true },
      downloadUrl: '',
      installPath: '',
      detectedInstallPath: '',
      isGui: false,
      programName: 'claude',
      binaryName: 'claude.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'opencode',
      name: 'OpenCode',
      description: '',
      logoPath: '',
      category: 'AI 编程',
      needDownload: false,
      source: { kind: 'scan', scanOnly: true },
      downloadUrl: '',
      installPath: '',
      detectedInstallPath: '',
      isGui: false,
      programName: 'opencode',
      binaryName: 'opencode.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'codex',
      name: 'Codex',
      description: '',
      logoPath: '',
      category: 'AI 编程',
      needDownload: false,
      source: { kind: 'scan', scanOnly: true },
      downloadUrl: '',
      installPath: '',
      detectedInstallPath: '',
      isGui: true,
      programName: 'codex',
      binaryName: 'Codex.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'claude-code',
      name: 'Claude Code',
      description: '',
      logoPath: '',
      category: 'AI 编程',
      needDownload: false,
      source: { kind: 'scan', scanOnly: true },
      downloadUrl: '',
      installPath: '',
      detectedInstallPath: '',
      isGui: false,
      programName: 'claude',
      binaryName: 'claude.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },    
    {
      id: 'vscode',
      name: 'VS Code',
      description: '',
      logoPath: '',
      category: 'IDE',
      needDownload: true,
      source: { kind: 'githubRelease', scanOnly: false, repo: 'Microsoft/vscode' },
      downloadUrl: 'https://github.com/Microsoft/vscode',
      installPath: '',
      detectedInstallPath: '',
      isGui: true,
      programName: 'Code',
      binaryName: 'Code.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'cursor',
      name: 'Cursor',
      description: '',
      logoPath: '',
      category: 'IDE',
      needDownload: false,
      installPath: '',
      detectedInstallPath: '',
      isGui: true,
      programName: 'Cursor',
      binaryName: 'Cursor.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'trae',
      name: 'Trae',
      description: '',
      logoPath: '',
      category: 'IDE',
      installPath: '',
      detectedInstallPath: '',
      isGui: true,
      needDownload: false,
      programName: 'Trae',
      binaryName: 'Trae.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'cc-switch',
      name: 'CC Switch',
      description: '',
      logoPath: '',
      category: '代理/网络',
      needDownload: true,
      source: {
        kind: 'githubRelease',
        scanOnly: false,
        repo: 'farion1231/cc-switch',
      },
      downloadUrl: 'https://github.com/farion1231/cc-switch',
      installPath: '',
      detectedInstallPath: '',
      isGui: true,
      programName: 'cc-switch',
      binaryName: 'cc-switch.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },    
    {
      id: 'codex-proxy',
      name: 'codex-proxy',
      description: '',
      logoPath: '',
      category: '代理/网络',
      needDownload: true,
      source: {
        kind: 'githubRelease',
        scanOnly: false,
        repo: 'icebear0828/codex-proxy',
      },
      downloadUrl: 'https://github.com/icebear0828/codex-proxy',
      installPath: '',
      detectedInstallPath: '',
      isGui: false,
      programName: 'codex-proxy',
      binaryName: 'codex-proxy.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'cliproxy',
      name: 'CLIProxy',
      description: '',
      logoPath: '',
      category: '代理/网络',
      needDownload: true,
      source: {
        kind: 'githubRelease',
        scanOnly: false,
        repo: 'router-for-me/CLIProxyAPI',
      },
      downloadUrl: 'https://github.com/router-for-me/CLIProxyAPI',
      installPath: '',
      detectedInstallPath: '',
      isGui: false,
      programName: 'cliproxy',
      binaryName: 'cliproxy.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'zero-limit',
      name: 'ZeroLimit',
      description: '',
      logoPath: '',
      category: '代理/网络',
      needDownload: true,
      source: { kind: 'githubRelease', scanOnly: false, repo: '0xtbug/zero-limit' },
      downloadUrl: 'https://github.com/0xtbug/zero-limit',
      installPath: '',
      detectedInstallPath: '',
      isGui: true,
      programName: 'zero-limit',
      binaryName: 'zero-limit.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'proxypilot',
      name: 'ProxyPilot',
      description: '',
      logoPath: '',
      category: '代理/网络',
      needDownload: true,
      source: {
        kind: 'githubRelease',
        scanOnly: false,
        repo: 'Finesssee/ProxyPilot',
      },
      downloadUrl: 'https://github.com/Finesssee/ProxyPilot',
      installPath: '',
      detectedInstallPath: '',
      isGui: true,
      programName: 'proxypilot',
      binaryName: 'ProxyPilot.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'open-design',
      name: 'OpenDesign',
      description: '',
      logoPath: '',
      category: '设计工具',
      needDownload: true,
      source: { kind: 'githubRelease', scanOnly: false, repo: 'nexu-io/open-design' },
      downloadUrl: 'https://github.com/nexu-io/open-design',
      installPath: '',
      detectedInstallPath: '',
      isGui: true,
      programName: 'open-design',
      binaryName: 'OpenDesign.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'wezterm',
      name: 'WezTerm',
      description: '',
      logoPath: '',
      category: '终端',
      needDownload: true,
      source: { kind: 'githubRelease', scanOnly: false, repo: 'wezterm/wezterm' },
      downloadUrl: 'https://github.com/wezterm/wezterm',
      installPath: '',
      detectedInstallPath: '',
      isGui: true,
      programName: 'wezterm',
      binaryName: 'wezterm.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'tabby',
      name: 'Tabby',
      description: '',
      logoPath: '',
      category: '终端',
      needDownload: true,
      source: { kind: 'githubRelease', scanOnly: false, repo: 'Eugeny/tabby' },
      downloadUrl: 'https://github.com/Eugeny/tabby',
      installPath: '',
      detectedInstallPath: '',
      isGui: true,
      programName: 'tabby',
      binaryName: 'Tabby.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'git',
      name: 'Git',
      description: '',
      logoPath: '',
      category: '终端',
      needDownload: true,
      source: { kind: 'githubRelease', scanOnly: false, repo: 'git-for-windows/git' },
      downloadUrl: 'https://github.com/git-for-windows/git',
      installPath: '',
      detectedInstallPath: '',
      isGui: false,
      programName: 'git',
      binaryName: 'git.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },     
  ];
}

/** 返回默认应用配置。 */
export function defaultConfig(): AppConfig {
  return {
    configVersion: 3,
    categories: defaultCategories(),
    repos: [],
    bookmarks: [],
    ui: {
      theme: 'dark',
      closeToTray: true,
    },
    download: {
      tempDir: '',
      concurrency: 3,
      notifyOnComplete: true,
    },
    proxy: defaultProxy(),
    env: {
      global: {},
      perTool: {},
    },
    terminal: {
      fontFamily: 'Consolas',
      fontSize: 13,
      renderer: 'canvas',
      gpu: true,
      colorScheme: 'TokyoNight',
      theme: 'dark',
    },
    advanced: {
      autoStart: false,
      logLevel: 'error',
      scanRoots: [],
      scanDepth: 10,
    },
    tools: defaultTools(),
  };
}
