import { type AppConfig, type ProxyConfig, type ToolMeta } from '@/shared/types';

function defaultProxy(): ProxyConfig {
  return {
    type: 'none',
    host: '',
    port: 0,
    username: '',
    password: '',
  };
}

/** 返回默认分类列表。 */
export function defaultCategories(): string[] {
  return ['AI 编程', '代理/网络', '设计工具', '终端'];
}

/** 返回默认工具列表。 */
export function defaultTools(): ToolMeta[] {
  return [
    {
      id: 'claude-code',
      name: 'Claude Code',
      description: '',
      logoPath: '',
      category: 'AI 编程',
      source: { kind: 'scan', scanOnly: true },
      downloadUrl: '',
      installPath: '',
      detectedInstallPath: '',
      isGui: false,
      programName: 'claude',
      binaryName: 'claude.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'opencode',
      name: 'OpenCode',
      description: '',
      logoPath: '',
      category: 'AI 编程',
      source: { kind: 'scan', scanOnly: true },
      downloadUrl: '',
      installPath: '',
      detectedInstallPath: '',
      isGui: false,
      programName: 'opencode',
      binaryName: 'opencode.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'codex',
      name: 'Codex',
      description: '',
      logoPath: '',
      category: 'AI 编程',
      source: { kind: 'scan', scanOnly: true },
      downloadUrl: '',
      installPath: '',
      detectedInstallPath: '',
      isGui: true,
      programName: 'codex',
      binaryName: 'Codex.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'cc-switch',
      name: 'CC Switch',
      description: '',
      logoPath: '',
      category: '代理/网络',
      source: { kind: 'githubRelease', scanOnly: false, repo: 'farion1231/cc-switch' },
      downloadUrl: 'https://github.com/farion1231/cc-switch',
      installPath: '',
      detectedInstallPath: '',
      isGui: true,
      programName: 'cc-switch',
      binaryName: 'cc-switch.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'codex-proxy',
      name: 'codex-proxy',
      description: '',
      logoPath: '',
      category: '代理/网络',
      source: {
        kind: 'githubRelease',
        scanOnly: false,
        repo: 'icebear0828/codex-proxy',
      },
      downloadUrl: 'https://github.com/icebear0828/codex-proxy',
      installPath: '',
      detectedInstallPath: '',
      isGui: false,
      programName: 'codex-proxy',
      binaryName: 'codex-proxy.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'cliproxy',
      name: 'CLIProxy',
      description: '',
      logoPath: '',
      category: '代理/网络',
      source: {
        kind: 'githubRelease',
        scanOnly: false,
        repo: 'router-for-me/CLIProxyAPI',
      },
      downloadUrl: 'https://github.com/router-for-me/CLIProxyAPI',
      installPath: '',
      detectedInstallPath: '',
      isGui: false,
      programName: 'cliproxy',
      binaryName: 'cliproxy.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'zero-limit',
      name: 'ZeroLimit',
      description: '',
      logoPath: '',
      category: '代理/网络',
      source: { kind: 'githubRelease', scanOnly: false, repo: '0xtbug/zero-limit' },
      downloadUrl: 'https://github.com/0xtbug/zero-limit',
      installPath: '',
      detectedInstallPath: '',
      isGui: true,
      programName: 'zero-limit',
      binaryName: 'zero-limit.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'proxypilot',
      name: 'ProxyPilot',
      description: '',
      logoPath: '',
      category: '代理/网络',
      source: {
        kind: 'githubRelease',
        scanOnly: false,
        repo: 'Finesssee/ProxyPilot',
      },
      downloadUrl: 'https://github.com/Finesssee/ProxyPilot',
      installPath: '',
      detectedInstallPath: '',
      isGui: true,
      programName: 'proxypilot',
      binaryName: 'ProxyPilot.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'open-design',
      name: 'OpenDesign',
      description: '',
      logoPath: '',
      category: '设计工具',
      source: { kind: 'githubRelease', scanOnly: false, repo: 'nexu-io/open-design' },
      downloadUrl: 'https://github.com/nexu-io/open-design',
      installPath: '',
      detectedInstallPath: '',
      isGui: true,
      programName: 'open-design',
      binaryName: 'OpenDesign.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
    {
      id: 'wezterm',
      name: 'WezTerm',
      description: '',
      logoPath: '',
      category: '终端',
      source: { kind: 'githubRelease', scanOnly: false, repo: 'wezterm/wezterm' },
      downloadUrl: 'https://github.com/wezterm/wezterm',
      installPath: '',
      detectedInstallPath: '',
      isGui: true,
      programName: 'wezterm',
      binaryName: 'wezterm.exe',
      args: [],
      env: {},
      proxy: defaultProxy(),
    },
  ];
}

/** 返回默认应用配置。 */
export function defaultConfig(): AppConfig {
  return {
    configVersion: 2,
    categories: defaultCategories(),
    ui: {
      theme: 'dark',
      closeToTray: true,
    },
    download: {
      tempDir: '',
      concurrency: 3,
      notifyOnComplete: true,
    },
    proxy: defaultProxy(),
    env: {
      global: {},
      perTool: {},
    },
    terminal: {
      renderer: 'canvas',
      gpu: true,
      theme: 'dark',
    },
    advanced: {
      autoStart: false,
      logLevel: 'error',
    },
    tools: defaultTools(),
  };
}
